### ISSUE TITLE
He can not sell a car

### ISSUE THREAD

**Issue by KesaCZ** [qalle-fivem/esx-qalle-sellvehicles#2]
He can not sell a car. Has the apartment in line 40 server/main.lua v.plate? If I switch to a plate, the car can be sold but I can not own it

**Comment by KesaCZ** [comment]
> He can not sell a car. Has the apartment in line 40 server/main.lua v.plate? If I switch to a plate, the car can be sold but I can not own it

I found a solution rewrite line 40 local plate = vehicleProps[“plate”] to local plate = vehicleProps.plate

**Comment by DioneB** [comment]
Same Problem here, and changing local plate = vehicleProps[“plate”] to local plate = vehicleProps.plate not works for me :/ I'm trying to understand the reason, if is an garage, Ls, etc.

**Comment by DioneB** [comment]
Solved, just replace to: 

	local plate = vehicleProps.plate
	plate = string.gsub(plate, "%s+", "")

if(plate == string.gsub(v.plate, "%s+", ""))then

**Comment by qalle-git** [comment]
I've fixed this with a Trim function.
