### ISSUE TITLE
Seller doesnt get money!!

### ISSUE THREAD

**Issue by gingygames** [qalle-fivem/esx-qalle-sellvehicles#3]
No errors client side or server side, latest version.

**Comment by benzon** [comment]
This can be confirmed, it happens randomly.

Either way, the seller should get money, and check's should be in place be fore the car is sold, i redid the buyVehicle part, to avoid further issues, and havent had issues since.

**Comment by gingygames** [comment]
On my server its never working.
Im using old vehicleshop (ID) version and inserting plates when saving cars in garage, but that shouldnt be the problem.

**Comment by amakuu** [comment]
same, im using the newest version, sometimes player just dont get money.

**Comment by N4nsh** [comment]
I have the same problem where some users complain of not getting the money after a vehicle has been sold.

**Comment by qalle-git** [comment]
If the player is online it gets the money. If the player is offline it gets the money. I've just tried both and both work.

**Comment by benzon** [comment]
The script breaks after 3-4 hours, and that is a fact, thos saying it's an issue is right - i have worked on this with a friend server from the US, and they have the same issue, it fails at somepoint.

Right now the solution we are working on, is logging the sales in the DB, and running a function on restart that gives the seller money, to avoid the issue further.
